import { NodeSDK } from "@opentelemetry/sdk-node";
import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { OTLPMetricExporter } from "@opentelemetry/exporter-metrics-otlp-http";
import { PeriodicExportingMetricReader } from "@opentelemetry/sdk-metrics";
import { Resource } from "@opentelemetry/resources";
import { ATTR_SERVICE_NAME } from "@opentelemetry/semantic-conventions";
import { metrics, trace } from "@opentelemetry/api";

let sdk: NodeSDK | null = null;

const meter = metrics.getMeter("ampm-worker");

export const aiPromptTokensCounter = meter.createCounter("ai_tokens_prompt_total", {
  description: "Total number of estimated prompt/input tokens or bytes analyzed",
});

export const aiCompletionTokensCounter = meter.createCounter("ai_tokens_completion_total", {
  description: "Total number of completion/output tokens generated by AI models",
});

export const aiTokensTotalCounter = meter.createCounter("ai_tokens_total", {
  description: "Total tokens (prompt + completion) processed across AI models",
});

export const aiRequestDurationHistogram = meter.createHistogram("ai_request_duration_ms", {
  description: "Duration of AI model inference requests in milliseconds",
  unit: "ms",
});

export interface AiTokenAnalysisPayload {
  provider: "huggingface" | "google_vision";
  model: string;
  task: "captioning" | "label_detection" | "content_safety";
  promptTokens: number;
  completionTokens: number;
  durationMs: number;
  isSuccess: boolean;
}

export function recordAiTokenAnalysis(payload: AiTokenAnalysisPayload): void {
  const { provider, model, task, promptTokens, completionTokens, durationMs, isSuccess } = payload;
  const status = isSuccess ? "success" : "failure";
  const totalTokens = promptTokens + completionTokens;

  aiPromptTokensCounter.add(promptTokens, { provider, model, task, status });
  aiCompletionTokensCounter.add(completionTokens, { provider, model, task, status });
  aiTokensTotalCounter.add(totalTokens, { provider, model, task, status });
  aiRequestDurationHistogram.record(durationMs, { provider, model, task, status });

  const activeSpan = trace.getActiveSpan();
  if (activeSpan) {
    activeSpan.setAttribute("ai.provider", provider);
    activeSpan.setAttribute("ai.model", model);
    activeSpan.setAttribute("ai.task", task);
    activeSpan.setAttribute("ai.tokens.prompt", promptTokens);
    activeSpan.setAttribute("ai.tokens.completion", completionTokens);
    activeSpan.setAttribute("ai.tokens.total", totalTokens);
    activeSpan.setAttribute("ai.duration_ms", durationMs);
    activeSpan.setAttribute("ai.status", status);
  }
}

export function initTelemetry(customServiceName?: string): NodeSDK | null {
  if (process.env.OTEL_SDK_DISABLED === "true") {
    return null;
  }

  if (sdk) {
    return sdk;
  }

  const serviceName = customServiceName || process.env.OTEL_SERVICE_NAME || "ampm-worker";
  const otlpEndpoint = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || "http://signoz-otel-collector:4318";

  const traceExporter = new OTLPTraceExporter({
    url: `${otlpEndpoint.replace(/\/$/, "")}/v1/traces`,
  });

  const metricExporter = new OTLPMetricExporter({
    url: `${otlpEndpoint.replace(/\/$/, "")}/v1/metrics`,
  });

  sdk = new NodeSDK({
    resource: new Resource({
      [ATTR_SERVICE_NAME]: serviceName,
    }),
    traceExporter,
    metricReader: new PeriodicExportingMetricReader({
      exporter: metricExporter,
      exportIntervalMillis: 5000,
    }),
    instrumentations: [
      getNodeAutoInstrumentations({
        "@opentelemetry/instrumentation-fs": { enabled: false },
      }),
    ],
  });

  try {
    sdk.start();
    console.log(`[Telemetry] OpenTelemetry initialized for ${serviceName} -> ${otlpEndpoint}`);
  } catch (error) {
    console.error("[Telemetry] Failed to start OpenTelemetry SDK:", error);
  }

  return sdk;
}

if (process.env.NODE_ENV !== "test" && process.env.OTEL_SDK_DISABLED !== "true") {
  initTelemetry();
}
